# manage plugin
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

# snippet
[[plugins]]
repo = 'SirVer/ultisnips'

# manage files
[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# preview markdown
[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

# tools
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'markonm/traces.vim'

# input japanese
[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = '''
autocmd User eskk-initialize-pre call s:eskk_initial_pre()
function! s:eskk_initial_pre()
  let t = eskk#table#new('rom_to_hira*', 'rom_to_hira')
  call t.add_map(',', '，')
  call t.add_map('.', '．')
  call eskk#register_mode_table('hira', t)
  let t = eskk#table#new('rom_to_kata*', 'rom_to_kata')
  call t.add_map(',', '，')
  call t.add_map('.', '．')
  call eskk#register_mode_table('kata', t)
endfunction
'''

# apperance
[[plugins]]
repo = 'itchyny/lightline.vim'
