[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
augroup MyLsp
  if executable('cquery')
    au User lsp_setup call lsp#register_server({
      \ 'name': 'cquery',
      \ 'cmd': {server_info->['cquery']},
      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
      \ 'initialization_options': { 'cacheDirectory': '/tmp/cquery/cache' },
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
      \ })
  endif

  autocmd FileType haskell setlocal omnifunc=lsp#complete
  if executable('hie')
    au User lsp_setup call lsp#register_server({
      \ 'name': 'hie',
      \ 'cmd': {server_info->['hie']},
      \ 'whitelist': ['haskell'],
      \ })
  endif
  au FileType haskell nmap <leader>R <plug>(lsp-rename)
  au FileType haskell nmap <leader>D <plug>(lsp-definition)
  au FileType haskell nmap <leader>r <plug>(lsp-references)
  au FileType haskell nmap <leader>d <plug>(lsp-document-symbol)
  au FileType haskell nmap <leader>w <plug>(lsp-workspace-symbol)
augroup end

let g:lsp_signs_enabled = 1         " enable signs
let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode

let g:lsp_signs_error = {'text': '??'}
let g:lsp_signs_warning = {'text': '!!'}

let g:asyncomplete_completion_delay=10
'''

[[plugins]]
repo = 'pdavydov108/vim-lsp-cquery'
hook_add = '''
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fv :LspCqueryDerived<CR>
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fc :LspCqueryCallers<CR>
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fb :LspCqueryBase<CR>
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fi :LspCqueryVars<CR>
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_linters = {
\   'c'      : ['cquery'],
\   'cpp'    : ['cquery'],
\   'haskell': ['hie'] }
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
