[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete'
hook_add = ''' " {{{
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_smart_case = 1
    let g:neocomplete#sources#syntax#min_keyword_length = 3
    inoremap <expr><Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    augroup OmniCompletionNeocompleteCommands
        autocmd!
        autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
        autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
        autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
        autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
        autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
    augroup END
''' # }}}

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['Shougo/neocomplete.vim']
#hook_add = ''' " {{{
#    imap <expr><CR> neosnippet#expandable_or_jumpable() ?
#        \ "\<Plug>(neosnippet_expand_or_jump)" :
#        \ "\<CR>"
#''' # }}}

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = ''' " {{{/*{{{*/
    let g:lightline = {
                \     'colorscheme': 'wombat',
                \     'active': {
                \         'left': [
                \             ['mode', 'paste'],
                \             ['readonly', 'filename', 'modified']
                \         ],
                \         'right': [
                \             ['lineinfo'],
                \             ['persent'],
                \             ['fileformat', 'fileencoding', 'filetype']
                \         ]
                \     },
                \     'component_function': {
                \         'filename': 'VimrcLightLineFileName'
                \     },
                \     'component_expand': {
                \         'readonly': 'VimrcLightLineReadOnly'
                \     },
                \     'component_type': {
                \         'readonly': 'error'
                \     }
                \ }
    
    function! VimrcLightLineReadOnly()
        return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'RO' : ''
    endfunction
    function! VimrcLightLineFileName()
        if &ft == 'vimfiler'
            return vimfiler#get_status_string()
        elseif &ft == 'unite'
            return unite#get_status_string()
        elseif expand('%') == ''
            return '[No Name]'
        else
            return expand('%')
        endif
    endfunction
''' # }}}/*}}}*/


[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

# for file management
[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vimproc.vim']
hook_add = ''' " {{{
    nmap <Space> [unite]
    autocmd FileType unite,vimfiler nnoremap <buffer> <silent> <ESC><ESC> :q<CR>
    autocmd FileType unite,vimfiler inoremap <buffer> <silent> <ESC><ESC> <ESC>:q<CR>
    let g:unite_force_overwrite_statusline = 0
    if executable('pt')
        let g:unite_source_grep_command = 'pt'
        let g:unite_source_grep_default_opts = '--nogroup --nocolor'
        let g:unite_source_grep_recursive_opt = ''
    elseif executable('ag')
        let g:unite_source_grep_command = 'ag'
        let g:unite_source_grep_default_opts = '-i --vimgrep --hidden --ignore' .
            \ ' ''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'' '
        let g:unite_source_grep_recursive_opt = ''
    endif
    nnoremap <silent> [unite]gg :<C-u>call <SID>unite_smart_grep_buffer_dir()<CR>
    function! s:unite_smart_grep_buffer_dir()
        if system('git rev-parse --is-inside-work-tree') == "true\n"
            exec ':Unite grep/git:' . expand('%:h')
        else
            exec ':Unite grep:' . expand('%:h')
        endif
    endfunction
''' # }}}

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = ['unite.vim']
hook_add = ''' " {{{
    let g:vimfiler_force_overwrite_statusline = 0
    let g:vimfiler_as_default_explorer = 1
    noremap <silent> [unite]ff :<C-u>VimFilerBufferDir<CR>
''' # }}}

[[plugins]]
repo = 'h1mesuke/unite-outline'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/syntastic'

# for foldering
[[plugins]]
repo = 'LeafCage/foldCC.vim'
hook_add = ''' " {{{
    set foldtext=FoldCCtext()
''' # }}}

[[plugins]]
repo = 'tomasr/molokai'
