# Prefix
set-option -g prefix C-a
## unlock default prefix(C-b)
unbind C-b
## press Ctrl-g*2 to send-prefix
bind C-a send-prefix

# KeyBindings
## the last window
bind C-q next-window

# reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# bind : to command-prompt like vim
# this is the default in tmux already
bind : command-prompt

# set key-binds of visual mode like vim
set-window-option -g mode-keys vi

# StatusBar
set-option -g status-interval 30

# Option
## Esc
set -s escape-time 0
set -sg escape-time 1
## control settings
setw -g monitor-activity on
set -g visual-activity on
set -g history-limit 10000
set -g automatic-rename off
set -g base-index 1
setw -g pane-base-index 1

# view setting
## Border
set -g pane-border-style fg=white
set -g pane-active-border-style fg=magenta
## true color
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
## status bar
set-option -g status-interval 30
set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=green,bg=#303031]#{?client_prefix,#[reverse],} #H[#S] #[default]'
set -g status-right '#[fg=green,bold][%Y/%m/%d(%a)%H:%M]#[default]'
## active border
set -g pane-active-border-style fg=black
set -g pane-active-border-style bg=green
set -g window-status-current-style bg=green
set -g window-status-current-style fg=white

# shell settings
set-option -g default-shell /usr/bin/zsh

# Terminal emulator window titles
set -g set-titles on
set -g set-titles-string "#T"

# mouse
set -g mouse on
bind-key m set-option -g mouse on \; display 'Mouse: ON'
bind-key M set-option -g mouse off \; display 'Mouse: OFF'

# copy and paste
## select by vi-style controls for copy mode with xclipboard
set -g mode-keys vi
## paste with xclipboard
bind-key c-p run "xsel -o | tmux load-buffer - ; tmux paste-buffer"

# https://github.com/catppuccin/tmux
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session user host date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"

# tmux-plugins/tmux-yank to yank
## List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'catppuccin/tmux'

## Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
