# Prefix
set-option -g prefix C-g
# unlock default prefix(C-b)
unbind C-b
# press Ctrl-g*2 to send-prefix
bind C-g send-prefix

# Option
# set key-binds of visual mode like vim
set-window-option -g mode-keys vi

# set the base number of pane
set-option -g base-index 1
# max line of history of windows
set-option -g history-limit 5000

# KeyBindings
# the last window
bind C-q next-window
# reload settings
#bind r source-file ~/.tmux.conf
#bind r source-file ~/.tmux.conf ; display-message "Reloaded!"

# split windows like vim
# vim's definition of horizontal/vertical split is reversed from tmux's
# split the pane longitudinary
bind s split-window -v
# split the pane transversely
bind v split-window -h

# move around panes with hjkl, as one would in vim after pressing ctrl-w
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# change syntax of resizing pane like vi
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10

# bind : to command-prompt like vim
# this is the default in tmux already
bind : command-prompt

# vi-style controls for copy mode
setw -g mode-keys vi

# Keybind(copy mode)
bind Space copy-mode
bind p paste-buffer

# StatusBar
set-option -g status-interval 30

# Border
set -g pane-border-style fg=white
set -g pane-active-border-style fg=magenta

# Other
## Esc
set -s escape-time 0

## control settings
set -g mode-keys vi
set -g automatic-rename off
set -sg escape-time 1

# color settings
#set-option -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm:colors=256'

# view settings
## status bar
set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=white,bg=black]#H#[fg=white]:#[fg=white][#S#[fg=white]]'
set -g status-right '#[fg=cyan,bold][%Y/%m/%d(%a)%H:%M]#[default]'
set-option -g status-left '#[fg=cyan,bg=#303030]#{?client_prefix,#[reverse],} #H[#S] #[default]'
## active border
set -g pane-active-border-style fg=black
set -g pane-active-border-style bg=cyan
set -g window-status-current-style bg=cyan
set -g window-status-current-style fg=white

# shell settings
set-option -g default-shell /usr/bin/zsh

# for emacs
unbind -t emacs-copy M-w
unbind -t emacs-copy C-w
bind-key -t emacs-copy M-w copy-pipe "xsel -bi"
bind-key -t emacs-copy C-w copy-pipe "xsel -bi"
