# Prefix
set-option -g prefix C-a
## unlock default prefix(C-b)
unbind C-b
## press Ctrl-g*2 to send-prefix
bind C-a send-prefix

# KeyBindings
## the last window
bind C-q next-window

# reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# easy-to-remember split pane commands
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# bind : to command-prompt like vim
# this is the default in tmux already
bind : command-prompt

# set key-binds of visual mode like vim
set-window-option -g mode-keys vi
## moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
## resize panes with vim movement keys
bind -r H resize-pane -L 10
bind -r J resize-pane -R 10
bind -r K resize-pane -D 10
bind -r L resize-pane -U 10

# StatusBar
set-option -g status-interval 30

# Option
## Esc
set -s escape-time 0
set -sg escape-time 1
## control settings
setw -g monitor-activity on
set -g visual-activity on
set -g history-limit 10000
set -g automatic-rename off
set -g base-index 1
setw -g pane-base-index 1

# view setting
## Border
set -g pane-border-style fg=white
set -g pane-active-border-style fg=magenta
## color
set -g default-terminal "tmux-256color"
set -g terminal-overrides 'xterm:colors=256'
## status bar
set-option -g status-interval 30
set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=green,bg=#303031]#{?client_prefix,#[reverse],} #H[#S] #[default]'
set -g status-right '#[fg=green,bold][%Y/%m/%d(%a)%H:%M]#[default]'
## active border
set -g pane-active-border-style fg=black
set -g pane-active-border-style bg=green
set -g window-status-current-style bg=green
set -g window-status-current-style fg=white

# shell settings
set-option -g default-shell /usr/bin/zsh

# vi-style controls for copy mode with xclipboard
set -g mode-keys vi
bind c copy-mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -ip && xsel -op | xsel -ib"

# mouse
set -g mouse on
bind-key m set-option -g mouse on \; display 'Mouse: ON'
bind-key M set-option -g mouse off \; display 'Mouse: OFF'
