[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']
external_commands = 'ghc-mod'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_source = ''' " {{{
    let g:vim_markdown_folding_disabled = 1
''' # }}}

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
