service buln
  {
    type    = UNLISTED
    protocol  = tcp
    socket_type = stream
    port    = 12345
    wait    = no

    server    = /usr/sbin/chroot
    server_args = /usr/chroot/ ./vuln
    user    = root
  }
