[[plugins]]
repo = 'Shougo/dein.vim'

[[plugsins]]
repo = 'Shougo/neocomplcache'
repo = 'Shougo/neocomplete'

repo = 'Shougo/vimproc'
build = 'make'

repo = 'Shougo/unite.vim'

repo = 'Shougo/neosnippet.vim'
repo = 'Shougo/neosnippet-snippets'

repo = 'nathanaeIkane/vim-indent-guides'

repo = 'thinca/vim-quickrun'

repo = 'h1mesuke/unite-outline'

repo = 'tpope/vim-fugitive'

repo = 'scrooloose/syntastic'

repo = 'w0ng/vim-hybrid'
