---
- name: install gtkrc-2.0
  copy:
    src: gtkrc-2.0
    dest: ~/.gtkrc-2.0

- name: create ~/.config/gtk-3.0 directory
  file:
    path: ~/.config/gtk-3.0
    state: directory

- name: install ~/.config/gtk-3.0/settings.ini
  copy:
    src: gtk-3.0/settings.ini
    dest: ~/.config/gtk-3.0/
