---
- name: create ~/.ssh directory
  file:
    path: ~/.ssh
    mode: 0700
    state: directory

- name: install ~/.ssh/known_hosts file
  copy:
    src: known_hosts
    dest: ~/.ssh/
    mode: 0600

- name: install ~/.ssh/config file
  copy:
    src: config
    dest: ~/.ssh/
    mode: 0600

- name: install authorized_keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ item }}"
  with_file:
    - extreme.pub
    - x201.pub

- name: install ssh-agent.service
  copy:
    src: ssh-agent.service
    dest: ~/.config/systemd/user/

- name: check if ssh-agent is enabled
  shell: systemctl --user is-enabled ssh-agent; true
  register: result
  changed_when: result.stdout == "disabled"

- name: enable ssh-agent service
  command: systemctl --user enable ssh-agent
  when: result.stdout is defined and result.stdout == "disabled"
