---
- name: install .vimperatorrc file
  copy:
    src: vimperatorrc
    dest: ~/.vimperatorrc
    mode: 0644

- name: create ~/.vimperator directory
  file:
    path: ~/.vimperator
    mode: 0755
    state: directory

- name: create ~/.vimperator/colors directory
  file:
    path: ~/.vimperator/colors
    mode: 0755
    state: directory

- name: install scheme.vimp file
  copy:
    src: scheme.vimp
    dest: ~/.vimperator/colors/
    mode: 0644
