---
- name: create ~/.uim.d directory
  file:
    path: ~/.uim.d
    mode: 0700
    state: directory

- name: create ~/.uim.d/customs directory
  file:
    path: ~/.uim.d/customs
    mode: 0700
    state: directory

- name: copy uim configuration files
  copy:
    src: "{{ item }}"
    dest: ~/.uim.d/customs/
    mode: 0644
  with_items:
    - custom-ajax-ime-advanced.scm
    - custom-ajax-ime-keys1.scm
    - custom-ajax-ime-keys2.scm
    - custom-ajax-ime-keys3.scm
    - custom-ajax-ime-keys4.scm
    - custom-ajax-ime.scm
    - custom-annotation.scm
    - custom-anthy-advanced.scm
    - custom-anthy-keys1.scm
    - custom-anthy-keys2.scm
    - custom-anthy-keys3.scm
    - custom-anthy-keys4.scm
    - custom-anthy-utf8.scm
    - custom-anthy.scm
    - custom-baidu-olime-jp-advanced.scm
    - custom-baidu-olime-jp-keys1.scm
    - custom-baidu-olime-jp-keys2.scm
    - custom-baidu-olime-jp-keys3.scm
    - custom-baidu-olime-jp-keys4.scm
    - custom-baidu-olime-jp.scm
    - custom-byeoru-keys1.scm
    - custom-byeoru-keys2.scm
    - custom-byeoru.scm
    - custom-elatin.scm
    - custom-global-keys1.scm
    - custom-global-keys2.scm
    - custom-global.scm
    - custom-google-cgiapi-jp-advanced.scm
    - custom-google-cgiapi-jp-keys1.scm
    - custom-google-cgiapi-jp-keys2.scm
    - custom-google-cgiapi-jp-keys3.scm
    - custom-google-cgiapi-jp-keys4.scm
    - custom-google-cgiapi-jp.scm
    - custom-http.scm
    - custom-ja-rk-rule.scm
    - custom-look-keys.scm
    - custom-look.scm
    - custom-m17nlib.scm
    - custom-notify.scm
    - custom-other-ims.scm
    - custom-predict.scm
    - custom-skk-advanced.scm
    - custom-skk-dict.scm
    - custom-skk-keys1.scm
    - custom-skk-keys2.scm
    - custom-skk-keys3.scm
    - custom-skk.scm
    - custom-social-ime-advanced.scm
    - custom-social-ime-keys1.scm
    - custom-social-ime-keys2.scm
    - custom-social-ime-keys3.scm
    - custom-social-ime-keys4.scm
    - custom-social-ime.scm
    - custom-toolbar.scm
    - custom-tutcode-keys1.scm
    - custom-tutcode-keys2.scm
    - custom-tutcode-keys3.scm
    - custom-tutcode-rule.scm
    - custom-tutcode.scm
    - custom-xim.scm
