---
- name: create ~/.xmonad directory
  file:
    path: ~/.xmonad
    mode: 0755
    state: directory

- name: install x-icon.png file
  copy:
    src: x-icon.png
    dest: ~/.xmonad/
    mode: 0644

- name: install xmonad.hs file
  copy:
    src: xmonad.hs
    dest: ~/.xmonad/
    mode: 0644
  notify: compile xmonad.hs

- name: create ~/.config/xmobar directory
  file:
    path: ~/.config/xmobar
    mode: 0755
    state: directory

- name: install xmobarrc file
  template:
    src: xmobarrc
    dest: ~/.config/xmobar/
    mode: 0644
