# Prefix
set-option -g prefix C-t
# unlock default prefix(C-b)
unbind C-b

# Option
# set key-binds of visual mode like vim
set-window-option -g mode-keys vi


# set the base number of pane
set-option -g base-index 1
# max line of history of windows
set-option -g history-limit 5000

# KeyBindings
# the last window
bind C-q next-window
# reload settings
#bind r source-file ~/.tmux.conf
#bind r source-file ~/.tmux.conf ; display-message "Reloaded!"

# split windows like vim
# vim's definition of horizontal/vertical split is reversed from tmux's
# split the pane longitudinary
bind s split-window -v
# split the pane transversely
bind v split-window -h

# move around panes with hjkl, as one would in vim after pressing ctrl-w
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# change syntax of resizing pane like vi
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10

# bind : to command-prompt like vim
# this is the default in tmux already
bind : command-prompt

# vi-style controls for copy mode
setw -g mode-keys vi


# Keybind(copy mode)
#
bind Space copy-mode
bind p paste-buffer
# start mark by v
bind -t vi-copy v begin-selection
# start mark for base-index by V
bind -t vi-copy V select-line
# switch visual mode by C-v
bind -t vi-copy C-v rectangle-toggle
# yank by y
bind -t vi-copy y copy-selection
# 1 line yank by Y
bind -t vi-copy Y copy-line












# Appearance
set-option -g default-terminal screen-256color

# StatusBar
set-option -g status-interval 30
set-option -g status-bg colour2
set-option -g status-fg black
set-window-option -g window-status-bg colour2
set-window-option -g window-status-fg black
set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-fg colour2

# Border
set -g pane-border-fg white
set -g pane-active-border-fg magenta

# Other
# Esc
set -s escape-time 0
