---
- name: add Qt config to Trolltech.conf
  ini_file:
    dest: ~/.config/Trolltech.conf
    section: Qt
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: font
      value: '"Sans Serif,9,-1,5,50,0,0,0,0,0"'
    - option: Palette\active
      value: "#000000, #d4d0c8, #ffffff, #e9e7e3, #6a6864, #a0a0a4, #000000, #ffffff, #000000, #ffffff, #d4d0c8, #000000, #000080, #ffffff, #0000ff, #ff00ff, #e9e7e3, #000000, #ffffdc, #000000"
    - option: Palette\inactive
      value: "#000000, #d4d0c8, #ffffff, #e9e7e3, #6a6864, #a0a0a4, #000000, #ffffff, #000000, #ffffff, #d4d0c8, #000000, #000080, #ffffff, #0000ff, #ff00ff, #e9e7e3, #000000, #ffffdc, #000000"
    - option: Palette\disabled
      value: "#6a6864, #d4d0c8, #ffffff, #e9e7e3, #6a6864, #a0a0a4, #6a6864, #ffffff, #6a6864, #d4d0c8, #d4d0c8, #000000, #000080, #ffffff, #0000ff, #ff00ff, #e9e7e3, #000000, #ffffdc, #000000"
    - option: fontPath
      value: "@Invalid()"
    - option: embedFonts
      value: "true"
    - option: style
      value: GTK+
    - option: doubleClickInterval
      value: 400
    - option: cursorFlashTime
      value: 1000
    - option: wheelScrollLines
      value: 3
    - option: resolveSymlinks
      value: "false"
    - option: globalStrut\width
      value: 0
    - option: globalStrut\height
      value: 0
    - option: useRtlExtensions
      value: "false"
    - option: XIMInputStyle
      value: "On The Spot"
    - option: DefaultInputMethod
      value: xim
    - option: audiosink
      value: Auto
    - option: videomode
      value: Auto
    - option: GUIEffects
      value: none
